### ISSUE TITLE
 Error! Error fetching Vehicle Configuration from [http://datastore-proxy-redhat-iot.router.default.svc.cluster.local/api/vehicles/]. Reload to retry

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [redhat-iot/summit2017#10]

**Comment by kamranIoTDeveloper** [comment]
Receiving three errors on accessing dashboard.
 Error! Error fetching Summaries Configuration from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/utils/summaries]. Reload to retry

 Error! Error fetching Facilities from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/facilities]. Reload to retry

 Error! Error fetching Vehicle Configuration from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/vehicles/]. Reload to retry

**Comment by jamesfalkner** [comment]
datastore-proxy-redhat-iot.router.default.svc.cluster.local Is not a valid hostname outside of the cluster - do you know why your route has that in there ?

**Comment by kamranIoTDeveloper** [comment]
What should be the valid hostname, it just appeared in openshift server when i installed iot-assettracking-demo
All other hostnames are also like this.
http://dashboard-redhat-iot.router.default.svc.cluster.local/
http://console-redhat-iot.router.default.svc.cluster.local/
http://api-redhat-iot.router.default.svc.cluster.local/
http://broker-redhat-iot.router.default.svc.cluster.local/

**Comment by jamesfalkner** [comment]
the default router subdomain is set when you install OpenShift and is used to set the route's externally-accessible hostname. It needs to be set to something 'external' (like `apps.<ipaddr>.nip.io`).

How did you install OpenShift? Are you using minishift?

**Comment by kamranIoTDeveloper** [comment]
I have installed Openshift Server by following instructions on official site of Openshift: https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary

Can i set router sub domain manually ?

**Comment by kamranIoTDeveloper** [comment]
Problem solved by changing sub domain manually
