### ISSUE TITLE
Prereq's

### ISSUE THREAD

**Issue by vap0rtranz** [redhat-iot/summit2017#6]
> If you see some components with "No Deployments" or are not building, you may need to add imagestream definitions for wildfly and jboss-datagrid

These stream requirements are indeed hard requirements for fresh CDK install (Wildfly and JDG streams).

**Comment by ccustine** [comment]
I think this depends on if you are using Origin or OCP builds so I am going to leave it as optional for now. We will be reviewing the steps and updating docs for 3.6 soon and will revisit this at that point.
