### ISSUE TITLE
datastore version 1.2 -> 1.4 in OpenShift 3.6

### ISSUE THREAD

**Issue by ikke-t** [redhat-iot/summit2017#8]
Hi,

I'm currently trying this. So far I noticed datastore will not build, as it has old version of jboss-datagrid-6/datagrid65-openshift. The one coming with OCP 3.6 is 1.4, which needs to be updated in deployment config.

Also I noticed minishift installs all jboss imagestreams, at least when using RH CDK. So the manual steps for that are not required while using RH CDK.

**Comment by ccustine** [comment]
Thanks for the report, I will test with OCP 3.6 and implement some backwards compatible solution.

**Comment by PatrickSteiner** [comment]
Is there already a fix?

I have a fresh OCP 3.6 and am seeing the following:

 - all pods start but "datastore"
 - deployment yaml for datastore says "image: 'registry.access.redhat.com/jboss-datagrid-6/datagrid65-openshift:1.2'"
 - ImageStream is called "jboss-datagrid65-openshift"

When I try to manually trigger a deployment of "datastore", I do get

```
[root@localhost summit2017]# oc rollout latest dc/datastore -n redhat-iot
Error from server (BadRequest): cannot trigger a deployment for "datastore" because it contains unresolved images
```

Is it something I'm doing wrong or is there a bug?

**Comment by ccustine** [comment]
If you git pull and run the deploy script again, this should be fixed. I believe you will also need to install the imagestreams if you are running origin. I have not tested this in 3.5/1.5 and earlier but most people will be starting in new minishift VMs or new dedicated clusters anyway.
